theme: minima
title: Autumn's Chart
author: Autumn Graves
email: graaja@bluffton.edu
description: Calendar that i have been working on in class!!


show_excerpts: true # set to false to remove excerpts on the homepage
